export const mainTheme = {
  token: {
    fontFamily: "Outfit, sans-serif",
  },
  components: {
    Menu: {
      iconSize: 24,
      itemActiveBg: "#F9FAFB",
      itemActiveColor: "#6A0DAD",
      itemHoverColor: "#F9FAFB",
      itemColor: "#F9FAFB",
      itemSelectedBg: "#F9FAFB",
      itemSelectedColor: "#6A0DAD",
      iconColor: "#F9FAFB",
      subMenuItemBg: "#F9FAFB11",
    },
    Form: {
      colorError: "#E53935",
    },
    Input: {
      colorTextPlaceholder: "#667085",
      colorIcon: "#6A0DAD",
    },
    Checkbox: {
      colorPrimary: "#6A0DAD",
      colorPrimaryHover: "#6A0DAD",
    },
    Select: {
      colorIcon: "#F9FAFB",
      colorBgContainer: "rgba(0,0,0,0)",
      fontSize: 20,
      optionSelectedColor: "#6A0DAD",
      optionSelectedBg: "#F9FAFB",
      optionActiveColor: "#F9FAFB",
      colorBorder: "#6A0DAD",
      colorBgElevated: "#6A0DAD",
      selectorBg: "#6A0DAD",
      colorText: "#6A0DAD",
      colorTextPlaceholder: "#F9FAFB",
      zIndexPopup: 990,
    },
    DatePicker: {
      fontSize: 20,
      colorBorder: "#6A0DAD",
      colorTextPlaceholder: "#6A0DAD",
    },
    Upload: {
      colorFillAlter: "rgba(0,0,0,0)",
      colorBorder: "#6A0DAD",
      colorBorderHover: "#6A0DAD",
      colorText: "#6A0DAD",
    },
    Table: {
      headerBorderRadius: 0,
      headerBg: "#6A0DAD",
      headerFilterHoverBg: "#F9FAFB88",
      headerSortActiveBg: "#6A0DADCC",
      headerSortHoverBg: "#6A0DADAA",
      colorBgContainer: "#F9FAFB",
      colorText: "#6A0DAD",
      borderColor: "#6A0DAD",
      headerColor: "#F9FAFB",
      fontSize: 18,
      footerColor: "#F9FAFB",
      colorIcon: "#F9FAFB",
      colorIconHover: "#F9FAFB",
      colorLinkActive: "#F9FAFB",
      headerSplitColor: "#262621",
    },
    Pagination: {
      itemActiveBg: "#6A0DAD",
      colorPrimary: "#F9FAFB",
      colorPrimaryHover: "#F9FAFB",
    },
  },
};
