export const tagTypes = {
  auth: "Auth",
  dashboard: "Dashboard",
  userManagement: "UserManagement",
  earning: "Earning",
  listing: "Listing",
  report: "Report",
  inspiration: "Inspiration",
  sponsorManagement: "SponsorManagement",
  conversation: "Conversation",
  sendNotification: "SendNotification",
  searchHistory: "SearchHistory",
  promotions: "Promotions",
  profile: "Profile",
  dataManagementUser: "DataManagementUser",
  dataManagementBusiness: "DataManagementBusiness",
  faq: "Faq",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.dashboard,
  tagTypes.userManagement,
  tagTypes.listing,
  tagTypes.earning,
  tagTypes.profile,
  tagTypes.report,
  tagTypes.inspiration,
  tagTypes.sponsorManagement,
  tagTypes.conversation,
  tagTypes.sendNotification,
  tagTypes.searchHistory,
  tagTypes.promotions,
  tagTypes.dataManagementUser,
  tagTypes.dataManagementBusiness,
  tagTypes.faq,
];
